Add user login authentication
HSNU-websites/repair_system pull request #15
Opened 2021-05-04 14:41 UTC by SiriusKoan

2021-05-04 15:05 UTC, william920429 requested changes
你 id 到底要存 id 還是 username？

2021-05-04 15:05 UTC, william920429 commented on app/users.py
> +    user.id = username
db_helper 回傳的是 id: int 欸

2021-05-04 15:05 UTC, william920429 commented on manage.py
> +    #     return
不用確定的嗎？
感覺有點危險

2021-05-04 15:11 UTC, SiriusKoan commented on manage.py
> +    #     return
我要讓 heroku 跑 reset，所以我只是註解掉，到時候上線再把他弄回來？

2021-05-04 15:21 UTC, william920429 requested changes
isAdmin

2021-05-04 15:21 UTC, william920429 commented on app/main/routes.py
> +                    if user_data["isAdmin"]:
isAdmin 也要存吧
不然一般user知道連結就可以進去了

2021-05-04 23:20 UTC, SiriusKoan commented on app/main/routes.py
> +                    if user_data["isAdmin"]:
噢噢對，我之後寫到 admin_required 之後會再加上去

2021-05-05 00:04 UTC, william920429 reviewed
.

2021-05-05 00:04 UTC, william920429 commented on manage.py
> +    #     return
那 manage.py reset -y ?

2021-05-05 00:10 UTC, SiriusKoan commented
> .

我覺得可以，回去修

2021-05-05 07:20 UTC, SiriusKoan commented on manage.py
> +    #     return
我覺得可以，晚點弄

2021-05-05 08:52 UTC, william920429 approved these changes
OK

2021-05-05 09:04 UTC, merged